version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net: